services:
  - type: web
    name: TAMY
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: DISCORD_WEBHOOK_URL
        sync: false 